/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class Game extends javax.swing.JFrame {
    
    String imagenes[]={
        "ahorcado_0.jpg",
        "ahorcado_1.jpg",
        "ahorcado_2.jpg",
        "ahorcado_3.jpg",
        "ahorcado_4.jpg",
        "ahorcado_5.jpg",
        "ahorcado_6.jpg"
    };
    
    int indice=0;
    

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        visor = new javax.swing.JLabel();
        btnA = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnÑ = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta5 = new javax.swing.JLabel();
        etiqueta3 = new javax.swing.JLabel();
        etiqueta4 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        etiqueta6 = new javax.swing.JLabel();
        etiqueta7 = new javax.swing.JLabel();
        etiqueta8 = new javax.swing.JLabel();
        etiqueta9 = new javax.swing.JLabel();
        etiqueta10 = new javax.swing.JLabel();
        etiqueta11 = new javax.swing.JLabel();
        etiqueta12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AHORCADO");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("¡JUGUEMOS!");

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton2.setText("SALIR DEL JUEGO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton1.setText("INICIAR JUEGO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        visor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        btnA.setText("A");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnS.setText("S");
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });

        btnD.setText("D");
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        btnF.setText("F");
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });

        btnG.setText("G");
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });

        btnH.setText("H");
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });

        btnJ.setText("J");
        btnJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJActionPerformed(evt);
            }
        });

        btnK.setText("K");
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });

        btnÑ.setText("Ñ");
        btnÑ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÑActionPerformed(evt);
            }
        });

        btnQ.setText("Q");
        btnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQActionPerformed(evt);
            }
        });

        btnW.setText("W");
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });

        btnE.setText("E");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnR.setText("R");
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });

        btnT.setText("T");
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        btnY.setText("Y");
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });

        btnU.setText("U");
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        btnI.setText("I");
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });

        btnO.setText("O");
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });

        btnP.setText("P");
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });

        btnZ.setText("Z");
        btnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZActionPerformed(evt);
            }
        });

        btnX.setText("X");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnV.setText("V");
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });

        btnB.setText("B");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        btnN.setText("N");
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });

        btnM.setText("M");
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setText("_   _   _   _   _   _   _   _   _   _   _   _");

        etiqueta1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        etiqueta5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        etiqueta3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        etiqueta4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        etiqueta2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        etiqueta6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        etiqueta7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        etiqueta8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        etiqueta9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        etiqueta10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        etiqueta11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        etiqueta12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton3.setText("CONTINUAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnÑ))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(etiqueta1)
                                    .addGap(18, 18, 18)
                                    .addComponent(etiqueta2)
                                    .addGap(18, 18, 18)
                                    .addComponent(etiqueta3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(etiqueta4)
                                    .addGap(18, 18, 18)
                                    .addComponent(etiqueta5)
                                    .addGap(15, 15, 15)
                                    .addComponent(etiqueta6)
                                    .addGap(16, 16, 16)
                                    .addComponent(etiqueta7)
                                    .addGap(14, 14, 14)
                                    .addComponent(etiqueta8)
                                    .addGap(18, 18, 18)
                                    .addComponent(etiqueta9)
                                    .addGap(19, 19, 19)
                                    .addComponent(etiqueta10)
                                    .addGap(19, 19, 19)
                                    .addComponent(etiqueta11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                                    .addComponent(etiqueta12)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnQ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnI)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnZ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnM)))
                .addGap(18, 18, 18)
                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton1)
                .addGap(48, 48, 48)
                .addComponent(jButton2)
                .addGap(38, 38, 38)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiqueta1)
                            .addComponent(etiqueta2)
                            .addComponent(etiqueta3)
                            .addComponent(etiqueta4)
                            .addComponent(etiqueta5)
                            .addComponent(etiqueta6)
                            .addComponent(etiqueta7)
                            .addComponent(etiqueta8)
                            .addComponent(etiqueta9)
                            .addComponent(etiqueta10)
                            .addComponent(etiqueta11)
                            .addComponent(etiqueta12))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnQ)
                            .addComponent(btnW)
                            .addComponent(btnE)
                            .addComponent(btnR)
                            .addComponent(btnT)
                            .addComponent(btnY)
                            .addComponent(btnU)
                            .addComponent(btnI)
                            .addComponent(btnO)
                            .addComponent(btnP))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnA)
                            .addComponent(btnS)
                            .addComponent(btnD)
                            .addComponent(btnF)
                            .addComponent(btnG)
                            .addComponent(btnH)
                            .addComponent(btnJ)
                            .addComponent(btnK)
                            .addComponent(btnÑ))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnZ)
                            .addComponent(btnX)
                            .addComponent(btnC)
                            .addComponent(btnV)
                            .addComponent(btnB)
                            .addComponent(btnN)
                            .addComponent(btnM))
                        .addGap(149, 149, 149))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
    }//GEN-LAST:event_btnDActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        // TODO add your handling code here:
        if(indice<6){
            letraR+="R";
            etiqueta2.setText(letraR);
            etiqueta5.setText(letraR);
            intentosP=intentosP+1;
            
            if(intentosP==9){
                JOptionPane.showMessageDialog(null, "¡HAS GANADO!");
            }else{
                JOptionPane.showMessageDialog(null, "ENCONTRASTE DOS LETRAS");
            }
        }else{
        
        }
    }//GEN-LAST:event_btnRActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu m=new Menu();
        m.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "LA PALABRA TIENE 12 LETRAS, LA PRIMER LETRA ES <P> Y LA ÚLTIMA ES <N>");
        JOptionPane.showMessageDialog(null, "TIENES 6 VIDAS, TE GUIARÁS POR LA IMAGEN, ¡SUERTE!");
        letraP="";
        letraR="";
        letraO="";
        letraG="";
        letraA="";
        letraM="";
        letraC="";
        letraI="";
        letraN="";
        etiqueta1.setText("");
        etiqueta2.setText("");
        etiqueta3.setText("");
        etiqueta4.setText("");
        etiqueta5.setText("");
        etiqueta6.setText("");
        etiqueta7.setText("");
        etiqueta8.setText("");
        etiqueta9.setText("");
        etiqueta10.setText("");
        etiqueta11.setText("");
        etiqueta12.setText("");
        ImageIcon imagen=new ImageIcon("ahorcado_0.jpg");
        visor.setIcon(imagen);
        indice=0;
        intentosP=0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnQ.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnQActionPerformed

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnW.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnWActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnE.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnEActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnT.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnTActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnY.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnYActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnU.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnUActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnS.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnSActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnF.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnFActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnH.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnHActionPerformed

    private void btnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnJ.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnJActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnK.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnKActionPerformed

    private void btnÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÑActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnÑ.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnÑActionPerformed

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnZ.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnZActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnX.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnXActionPerformed

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnV.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnVActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
        if(indice==6) indice=6;
        else indice++;
        ImageIcon Imagen=new ImageIcon(imagenes[indice]);
        visor.setIcon(Imagen);
        btnB.setEnabled(false);
        if(indice==6){
            JOptionPane.showMessageDialog(null, "¡PERDISTE!");
        }
    }//GEN-LAST:event_btnBActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        // TODO add your handling code here:
        if(indice<6){
            letraM+="M";
            etiqueta7.setText(letraM);
            intentosP=intentosP+1;
            
            if(intentosP==9){
                if(indice==0){
                    pfinal=6;
                }else if(indice==1){
                    pfinal=5;
                }else if(indice==2){
                    pfinal=4;
                }else if(indice==3){
                    pfinal=3;
                }else if(indice==4){
                    pfinal=2;
                }else if(indice==5){
                    pfinal=1;
                }
                JOptionPane.showMessageDialog(null, "¡HAS GANADO!");
                JOptionPane.showMessageDialog(null, "TERMINASTE CON "+pfinal+" PUNTOS DE PUNTUACION, ¡RECUERDALO Y DA CLICK A CONTINUAR SI DESEAS GUARDAR TU SCORE!");
            }else{
                JOptionPane.showMessageDialog(null, "ENCONTRASTE UNA LETRA");
            }
        }else{
        
        }
        btnM.setEnabled(false);
    }//GEN-LAST:event_btnMActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        // TODO add your handling code here:
        if(indice<6){
            letraO+="O";
            etiqueta3.setText(letraO);
            etiqueta11.setText(letraO);
            intentosP=intentosP+1;
            
            if(intentosP==9){
                if(indice==0){
                    pfinal=6;
                }else if(indice==1){
                    pfinal=5;
                }else if(indice==2){
                    pfinal=4;
                }else if(indice==3){
                    pfinal=3;
                }else if(indice==4){
                    pfinal=2;
                }else if(indice==5){
                    pfinal=1;
                }
                JOptionPane.showMessageDialog(null, "¡HAS GANADO!");
                JOptionPane.showMessageDialog(null, "TERMINASTE CON "+pfinal+" PUNTOS DE PUNTUACION, ¡RECUERDALO Y DA CLICK A CONTINUAR SI DESEAS GUARDAR TU SCORE!");
            }else{
                JOptionPane.showMessageDialog(null, "ENCONTRASTE DOS LETRAS");
            }
        }else{
        
        }
        btnO.setEnabled(false);
    }//GEN-LAST:event_btnOActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
        if(indice<6){
            letraA+="A";
            etiqueta6.setText(letraA);
            etiqueta8.setText(letraA);
            intentosP=intentosP+1;
            
            if(intentosP==9){
                if(indice==0){
                    pfinal=6;
                }else if(indice==1){
                    pfinal=5;
                }else if(indice==2){
                    pfinal=4;
                }else if(indice==3){
                    pfinal=3;
                }else if(indice==4){
                    pfinal=2;
                }else if(indice==5){
                    pfinal=1;
                }
                JOptionPane.showMessageDialog(null, "¡HAS GANADO!");
                JOptionPane.showMessageDialog(null, "TERMINASTE CON "+pfinal+" PUNTOS DE PUNTUACION, ¡RECUERDALO Y DA CLICK A CONTINUAR SI DESEAS GUARDAR TU SCORE!");
            }else{
                JOptionPane.showMessageDialog(null, "ENCONTRASTEDOS LETRAS");
            }
        }else{
        
        }
        btnA.setEnabled(false);
    }//GEN-LAST:event_btnAActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        // TODO add your handling code here:
        if(indice<6){
            letraP+="P";
            etiqueta1.setText(letraP);
            intentosP=intentosP+1;
            
            if(intentosP==9){
                if(indice==0){
                    pfinal=6;
                }else if(indice==1){
                    pfinal=5;
                }else if(indice==2){
                    pfinal=4;
                }else if(indice==3){
                    pfinal=3;
                }else if(indice==4){
                    pfinal=2;
                }else if(indice==5){
                    pfinal=1;
                }
                JOptionPane.showMessageDialog(null, "¡HAS GANADO!");
                JOptionPane.showMessageDialog(null, "TERMINASTE CON "+pfinal+" PUNTOS DE PUNTUACION, ¡RECUERDALO Y DA CLICK A CONTINUAR SI DESEAS GUARDAR TU SCORE!");
            }else{
                JOptionPane.showMessageDialog(null, "ENCONTRASTE UNA LETRA");
            }
        }else{
        
        }
        btnP.setEnabled(false);
    }//GEN-LAST:event_btnPActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        // TODO add your handling code here:
        if(indice<6){
            letraG+="G";
            etiqueta4.setText(letraG);
            intentosP=intentosP+1;
  
            if(intentosP==9){
                if(indice==0){
                    pfinal=6;
                }else if(indice==1){
                    pfinal=5;
                }else if(indice==2){
                    pfinal=4;
                }else if(indice==3){
                    pfinal=3;
                }else if(indice==4){
                    pfinal=2;
                }else if(indice==5){
                    pfinal=1;
                }
                JOptionPane.showMessageDialog(null, "¡HAS GANADO!");
                JOptionPane.showMessageDialog(null, "TERMINASTE CON "+pfinal+" PUNTOS DE PUNTUACION, ¡RECUERDALO Y DA CLICK A CONTINUAR SI DESEAS GUARDAR TU SCORE!");
            }else{
                JOptionPane.showMessageDialog(null, "ENCONTRASTE UNA LETRA");
            }
        }else{
        
        }
        btnG.setEnabled(false);
    }//GEN-LAST:event_btnGActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        if(indice<6){
            letraC+="C";
            etiqueta9.setText(letraC);
            intentosP=intentosP+1;
            
            if(intentosP==9){
                if(indice==0){
                    pfinal=6;
                }else if(indice==1){
                    pfinal=5;
                }else if(indice==2){
                    pfinal=4;
                }else if(indice==3){
                    pfinal=3;
                }else if(indice==4){
                    pfinal=2;
                }else if(indice==5){
                    pfinal=1;
                }
                JOptionPane.showMessageDialog(null, "¡HAS GANADO!");
                JOptionPane.showMessageDialog(null, "TERMINASTE CON "+pfinal+" PUNTOS DE PUNTUACION, ¡RECUERDALO Y DA CLICK A CONTINUAR SI DESEAS GUARDAR TU SCORE!");
            }else{
                JOptionPane.showMessageDialog(null, "ENCONTRASTE UNA LETRA");
            }
        }else{
        
        }
        btnC.setEnabled(false);
    }//GEN-LAST:event_btnCActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
        // TODO add your handling code here:
        if(indice<6){
            letraI+="I";
            etiqueta10.setText(letraI);
            intentosP=intentosP+1;
            
            if(intentosP==9){
                if(indice==0){
                    pfinal=6;
                }else if(indice==1){
                    pfinal=5;
                }else if(indice==2){
                    pfinal=4;
                }else if(indice==3){
                    pfinal=3;
                }else if(indice==4){
                    pfinal=2;
                }else if(indice==5){
                    pfinal=1;
                }
                JOptionPane.showMessageDialog(null, "¡HAS GANADO!");
                JOptionPane.showMessageDialog(null, "TERMINASTE CON "+pfinal+" PUNTOS DE PUNTUACION, ¡RECUERDALO Y DA CLICK A CONTINUAR SI DESEAS GUARDAR TU SCORE!");
            }else{
                JOptionPane.showMessageDialog(null, "ENCONTRASTE UNA LETRA");
            }
        }else{
        
        }
        btnI.setEnabled(false);
    }//GEN-LAST:event_btnIActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        // TODO add your handling code here:
        if(indice<6){
            letraN+="N";
            etiqueta12.setText(letraN);
            intentosP=intentosP+1;
            
            if(intentosP==9){
                if(indice==0){
                    pfinal=6;
                }else if(indice==1){
                    pfinal=5;
                }else if(indice==2){
                    pfinal=4;
                }else if(indice==3){
                    pfinal=3;
                }else if(indice==4){
                    pfinal=2;
                }else if(indice==5){
                    pfinal=1;
                }
                JOptionPane.showMessageDialog(null, "¡HAS GANADO!");
                JOptionPane.showMessageDialog(null, "TERMINASTE CON "+pfinal+" PUNTOS DE PUNTUACION, ¡RECUERDALO Y DA CLICK A CONTINUAR!");
            }else{
                JOptionPane.showMessageDialog(null, "ENCONTRASTE UNA LETRA");
            }
        }else{
            
        }
        btnN.setEnabled(false);
    }//GEN-LAST:event_btnNActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Datos d=new Datos();
        d.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }
    
    /*public void obtenerDatos(){
        String nombre=name.getText();
        int edad=Integer.parseInt(age.getText());
        int puntucacion=Integer.parseInt(score.getText());
        Datos d=new Datos();
        d.recibeDatos(nombre, edad, puntucacion);
    }*/
    
    int intentosP=0;
    int pfinal=0;
    String letraP="";
    String letraR="";
    String letraO="";
    String letraG="";
    String letraA="";
    String letraM="";
    String letraC="";
    String letraI="";
    String letraN="";
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JButton btnÑ;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta10;
    private javax.swing.JLabel etiqueta11;
    private javax.swing.JLabel etiqueta12;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiqueta3;
    private javax.swing.JLabel etiqueta4;
    private javax.swing.JLabel etiqueta5;
    private javax.swing.JLabel etiqueta6;
    private javax.swing.JLabel etiqueta7;
    private javax.swing.JLabel etiqueta8;
    private javax.swing.JLabel etiqueta9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel visor;
    // End of variables declaration//GEN-END:variables
}
